export const COMMON_CONFIG='COMMON_CONFIG';
export const HOME_GET_SWIPE_IMG='HOME_GET_SWIPE_IMG';
export const FRIEND_GET_LIST='FRIEND_GET_LIST';
export const FRIEND_ADD_LIST='FRIEND_ADD_LIST';
export const PERSONAL_INFO='PERSONAL_INFO';
export const FRIEND_UPDATED_LIST='FRIEND_UPDATED_LIST';